name: Generate PDFs

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    name: Build and Publish PDF
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        work_in_root_file_dir: true
        root_file: |
          ./latex/${{ matrix.directory }}/main.tex

    - name: Commit generated PDF
      run: ./commit-and-push.sh "[CI] Generate PDF for ${{ matrix.directory }}"